[book]
authors = ["Triton Software AG"]
language = "en"
src = "src"
title = "Triton Assembly Tutorial"

[preprocessor.triton-playground]
command = "cargo run --quiet --manifest-path tools/mdbook-triton-playground/Cargo.toml --"

[output.html]
git-repository-url = "https://github.com/TritonVM/triton-vm/tree/master/tutorial"
additional-css = ["custom.css"]
