use std::fmt::Display;
use std::mem::MaybeUninit;

use itertools::Itertools;
use ndarray::parallel::prelude::*;
use ndarray::Array1;
use ndarray::ArrayView1;
use ndarray::ArrayView2;
use ndarray::ArrayViewMut2;
use ndarray::Axis;
use twenty_first::shared_math::b_field_element::BFieldElement;
use twenty_first::shared_math::mpolynomial::Degree;
use twenty_first::shared_math::traits::FiniteField;
use twenty_first::shared_math::x_field_element::XFieldElement;

use crate::arithmetic_domain::ArithmeticDomain;
use crate::table::challenges::Challenges;

const ERROR_MESSAGE_GENERATE_CONSTRAINTS: &str =
    "Constraints must be in place. Run: `cargo run --bin constraint-evaluation-generator`";
const ERROR_MESSAGE_GENERATE_DEGREE_BOUNDS: &str =
    "Degree bounds must be in place. Run: `cargo run --bin constraint-evaluation-generator`";

pub trait Evaluable<FF: FiniteField> {
    /// The code for this method must be generated by running
    /// `cargo run --bin constraint-evaluation-generator`
    fn evaluate_initial_constraints(
        _base_row: ArrayView1<FF>,
        _ext_row: ArrayView1<XFieldElement>,
        _challenges: &Challenges,
    ) -> Vec<XFieldElement> {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }

    /// The code for this method must be generated by running
    /// `cargo run --bin constraint-evaluation-generator`
    fn evaluate_consistency_constraints(
        _base_row: ArrayView1<FF>,
        _ext_row: ArrayView1<XFieldElement>,
        _challenges: &Challenges,
    ) -> Vec<XFieldElement> {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }

    /// The code for this method must be generated by running
    /// `cargo run --bin constraint-evaluation-generator`
    fn evaluate_transition_constraints(
        _current_base_row: ArrayView1<FF>,
        _current_ext_row: ArrayView1<XFieldElement>,
        _next_base_row: ArrayView1<FF>,
        _next_ext_row: ArrayView1<XFieldElement>,
        _challenges: &Challenges,
    ) -> Vec<XFieldElement> {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }

    /// The code for this method must be generated by running
    /// `cargo run --bin constraint-evaluation-generator`
    fn evaluate_terminal_constraints(
        _base_row: ArrayView1<FF>,
        _ext_row: ArrayView1<XFieldElement>,
        _challenges: &Challenges,
    ) -> Vec<XFieldElement> {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }
}

pub trait Quotientable: Evaluable<BFieldElement> {
    /// Compute the degrees of the quotients from all AIR constraints that apply to the table.
    fn all_degrees_with_origin(
        table_name: &str,
        interpolant_degree: Degree,
        padded_height: usize,
    ) -> Vec<DegreeWithOrigin> {
        let initial_degrees_with_origin = Self::initial_quotient_degree_bounds(interpolant_degree)
            .into_iter()
            .enumerate()
            .map(|(i, d)| DegreeWithOrigin {
                degree: d,
                interpolant_degree,
                zerofier_degree: 1,
                origin_table_name: table_name.to_owned(),
                origin_index: i,
                origin_table_height: padded_height,
                origin_constraint_type: ConstraintType::Initial,
            })
            .collect_vec();

        let consistency_degrees_with_origin =
            Self::consistency_quotient_degree_bounds(interpolant_degree, padded_height)
                .into_iter()
                .enumerate()
                .map(|(i, d)| DegreeWithOrigin {
                    degree: d,
                    interpolant_degree,
                    zerofier_degree: padded_height as Degree,
                    origin_table_name: table_name.to_owned(),
                    origin_index: i,
                    origin_table_height: padded_height,
                    origin_constraint_type: ConstraintType::Consistency,
                })
                .collect();

        let transition_degrees_with_origin =
            Self::transition_quotient_degree_bounds(interpolant_degree, padded_height)
                .into_iter()
                .enumerate()
                .map(|(i, d)| DegreeWithOrigin {
                    degree: d,
                    interpolant_degree,
                    zerofier_degree: padded_height as Degree - 1,
                    origin_table_name: table_name.to_owned(),
                    origin_index: i,
                    origin_table_height: padded_height,
                    origin_constraint_type: ConstraintType::Transition,
                })
                .collect();

        let terminal_degrees_with_origin =
            Self::terminal_quotient_degree_bounds(interpolant_degree)
                .into_iter()
                .enumerate()
                .map(|(i, d)| DegreeWithOrigin {
                    degree: d,
                    interpolant_degree,
                    zerofier_degree: 1,
                    origin_table_name: table_name.to_owned(),
                    origin_index: i,
                    origin_table_height: padded_height,
                    origin_constraint_type: ConstraintType::Terminal,
                })
                .collect();

        [
            initial_degrees_with_origin,
            consistency_degrees_with_origin,
            transition_degrees_with_origin,
            terminal_degrees_with_origin,
        ]
        .concat()
    }

    fn fill_initial_quotients(
        master_base_table: ArrayView2<BFieldElement>,
        master_ext_table: ArrayView2<XFieldElement>,
        quot_table: &mut ArrayViewMut2<MaybeUninit<XFieldElement>>,
        zerofier_inverse: ArrayView1<BFieldElement>,
        challenges: &Challenges,
    ) {
        debug_assert_eq!(zerofier_inverse.len(), master_base_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), master_ext_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), quot_table.nrows());
        quot_table
            .axis_iter_mut(Axis(0))
            .into_par_iter()
            .enumerate()
            .for_each(|(row_index, quotient_table_row)| {
                let base_row = master_base_table.row(row_index);
                let ext_row = master_ext_table.row(row_index);
                Self::evaluate_initial_constraints(base_row, ext_row, challenges)
                    .into_iter()
                    .map(|numerator| numerator * zerofier_inverse[row_index])
                    .map(MaybeUninit::new)
                    .collect::<Array1<_>>()
                    .move_into(quotient_table_row);
            });
    }

    fn fill_consistency_quotients(
        master_base_table: ArrayView2<BFieldElement>,
        master_ext_table: ArrayView2<XFieldElement>,
        quot_table: &mut ArrayViewMut2<MaybeUninit<XFieldElement>>,
        zerofier_inverse: ArrayView1<BFieldElement>,
        challenges: &Challenges,
    ) {
        debug_assert_eq!(zerofier_inverse.len(), master_base_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), master_ext_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), quot_table.nrows());
        quot_table
            .axis_iter_mut(Axis(0))
            .into_par_iter()
            .enumerate()
            .for_each(|(row_index, quotient_table_row)| {
                let base_row = master_base_table.row(row_index);
                let ext_row = master_ext_table.row(row_index);
                Self::evaluate_consistency_constraints(base_row, ext_row, challenges)
                    .into_iter()
                    .map(|numerator| numerator * zerofier_inverse[row_index])
                    .map(MaybeUninit::new)
                    .collect::<Array1<_>>()
                    .move_into(quotient_table_row);
            });
    }

    fn fill_transition_quotients(
        master_base_table: ArrayView2<BFieldElement>,
        master_ext_table: ArrayView2<XFieldElement>,
        quot_table: &mut ArrayViewMut2<MaybeUninit<XFieldElement>>,
        zerofier_inverse: ArrayView1<BFieldElement>,
        challenges: &Challenges,
        trace_domain: ArithmeticDomain,
        quotient_domain: ArithmeticDomain,
    ) {
        debug_assert_eq!(zerofier_inverse.len(), master_base_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), master_ext_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), quot_table.nrows());

        // the relation between the quotient domain and the trace domain
        let unit_distance = quotient_domain.length / trace_domain.length;
        let domain_length_bit_mask = quotient_domain.length - 1;

        quot_table
            .axis_iter_mut(Axis(0))
            .into_par_iter()
            .enumerate()
            .for_each(|(current_row_index, quotient_table_row)| {
                // bitwise logical and `domain_length_bit_mask` performs the modulo operation:
                // `domain.length - 1` is a bit-mask with all 1s because `domain.length` is 2^k
                // for some k.
                let next_row_index = (current_row_index + unit_distance) & domain_length_bit_mask;
                Self::evaluate_transition_constraints(
                    master_base_table.row(current_row_index),
                    master_ext_table.row(current_row_index),
                    master_base_table.row(next_row_index),
                    master_ext_table.row(next_row_index),
                    challenges,
                )
                .into_iter()
                .map(|numerator| numerator * zerofier_inverse[current_row_index])
                .map(MaybeUninit::new)
                .collect::<Array1<_>>()
                .move_into(quotient_table_row);
            });
    }

    fn fill_terminal_quotients(
        master_base_table: ArrayView2<BFieldElement>,
        master_ext_table: ArrayView2<XFieldElement>,
        quot_table: &mut ArrayViewMut2<MaybeUninit<XFieldElement>>,
        zerofier_inverse: ArrayView1<BFieldElement>,
        challenges: &Challenges,
    ) {
        debug_assert_eq!(zerofier_inverse.len(), master_base_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), master_ext_table.nrows());
        debug_assert_eq!(zerofier_inverse.len(), quot_table.nrows());
        quot_table
            .axis_iter_mut(Axis(0))
            .into_par_iter()
            .enumerate()
            .for_each(|(row_index, quotient_table_row)| {
                let base_row = master_base_table.row(row_index);
                let ext_row = master_ext_table.row(row_index);
                Self::evaluate_terminal_constraints(base_row, ext_row, challenges)
                    .into_iter()
                    .map(|numerator| numerator * zerofier_inverse[row_index])
                    .map(MaybeUninit::new)
                    .collect::<Array1<_>>()
                    .move_into(quotient_table_row);
            });
    }

    fn num_initial_quotients() -> usize {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }

    fn num_consistency_quotients() -> usize {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }

    fn num_transition_quotients() -> usize {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }

    fn num_terminal_quotients() -> usize {
        panic!("{ERROR_MESSAGE_GENERATE_CONSTRAINTS}")
    }

    fn initial_quotient_degree_bounds(_interpolant_degree: Degree) -> Vec<Degree> {
        panic!("{ERROR_MESSAGE_GENERATE_DEGREE_BOUNDS}")
    }

    fn consistency_quotient_degree_bounds(
        _interpolant_degree: Degree,
        _padded_height: usize,
    ) -> Vec<Degree> {
        panic!("{ERROR_MESSAGE_GENERATE_DEGREE_BOUNDS}")
    }

    fn transition_quotient_degree_bounds(
        _interpolant_degree: Degree,
        _padded_height: usize,
    ) -> Vec<Degree> {
        panic!("{ERROR_MESSAGE_GENERATE_DEGREE_BOUNDS}")
    }

    fn terminal_quotient_degree_bounds(_interpolant_degree: Degree) -> Vec<Degree> {
        panic!("{ERROR_MESSAGE_GENERATE_DEGREE_BOUNDS}")
    }
}

/// The type of a constraint. Can be used to determine the degree bounds for the quotient
/// polynomials. Concretely, the degree of the zerofier polynomials differs between the
/// constraint types.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum ConstraintType {
    Initial,
    Consistency,
    Transition,
    Terminal,
}

impl Display for ConstraintType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConstraintType::Initial => write!(f, "initial"),
            ConstraintType::Consistency => write!(f, "consistency"),
            ConstraintType::Transition => write!(f, "transition"),
            ConstraintType::Terminal => write!(f, "terminal"),
        }
    }
}

/// Helps debugging and benchmarking. The maximal degree achieved in any table dictates the length
/// of the FRI domain, which in turn is responsible for the main performance bottleneck.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub struct DegreeWithOrigin {
    pub degree: Degree,
    pub interpolant_degree: Degree,
    pub zerofier_degree: Degree,
    pub origin_table_name: String,
    pub origin_index: usize,
    pub origin_table_height: usize,
    pub origin_constraint_type: ConstraintType,
}

impl Display for DegreeWithOrigin {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let zerofier_corrected_degree = self.degree + self.zerofier_degree;
        let degree = if self.interpolant_degree != 0 {
            zerofier_corrected_degree / self.interpolant_degree
        } else {
            zerofier_corrected_degree
        };
        write!(
            f,
            "Degree of poly for table {} (index {:02}) of type “{}” is {}.",
            self.origin_table_name, self.origin_index, self.origin_constraint_type, degree,
        )
    }
}
