name: Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install nightly toolchain
        run: rustup install nightly

      - name: Add component llvm-tools-preview
        run: rustup component add llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@a2352fc6ce487f030a3aa709482d57823eadfb37 # v2.75.16
        with:
          tool: cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@a2352fc6ce487f030a3aa709482d57823eadfb37 # v2.75.16
        with:
          tool: nextest

      - name: Collect coverage data
        run: cargo +nightly llvm-cov nextest --lcov --output-path lcov.info

      - name: Upload coverage to coveralls.io
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6

      - name: Archive coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: lcov.info
