name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    name: Build, lint, test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install stable toolchain
        run: rustup install

      - name: Add component rustfmt
        run: rustup component add rustfmt

      - name: Add component clippy
        run: rustup component add clippy

      - name: Install nextest
        uses: taiki-e/install-action@a2352fc6ce487f030a3aa709482d57823eadfb37 # v2.75.16
        with:
          tool: nextest

      - name: Check max line length
        # rustfmt gives up on lines that are too long
        if: runner.os == 'Linux'
        run: "! grep -rP '^.{101}' --include='*.rs' ."

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Build documentation
        run: cargo doc --no-deps --workspace --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: cargo nextest run --no-fail-fast --all-targets

        # doctests are special [^1] but this step does not incur a performance penalty [^2]
        #
        # [^1]: https://nexte.st/book/usage.html#limitations
        # [^2]: https://github.com/nextest-rs/nextest/issues/16
      - name: Run documentation tests
        run: cargo test --doc
